sohot_options: {
  max_depth: [5, 6, 7],
  smooth_step_param: [1, 10],
  alpha: [0.3, 0.4]
}
hoeffding_tree_options: {
  grace_period: [200, 400, 600],
  confidence: [1e-3, 1e-4],
  leaf_prediction: ['MajorityClass', 'NaiveBayesAdaptive']
}
hoeffding_tree_limit_options: {
  grace_period: [200, 400, 600],
  confidence: [1e-3, 1e-4],
  leaf_prediction: ['MajorityClass', 'NaiveBayesAdaptive'],
  node_limit: [255],
  depth_limit: [7]
}
EFDT_options: {
  grace_period: [200, 400, 600],
  min_samples_reevaluate: [200, 600],
  leaf_prediction: ['NaiveBayesAdaptive', 'MajorityClass']
}
hat_options: {
  grace_period: [200, 400, 600],
  confidence: [1e-3, 1e-4],
  leaf_prediction: ['MajorityClass', 'NaiveBayesAdaptive']
}
sgd_clf_options: {
  loss: ['log_loss', 'modified_huber'],
  penalty: ['l2', 'l1'],
  learning_rate: [
    {lr: 'optimal', eta0: 0.0},
    {lr: 'constant', eta0: 0.01},
    {lr: 'constant', eta0: 0.001}
    ]
}
tel_options: {
  max_depth: [5, 6, 7],
  smooth_step_param: [1, 10],
  learning_rate: [1e-2, 1e-3]
}
hoeffding_tree_reg_options: {
  grace_period: [200, 400, 600],
  confidence: [1e-3, 1e-4],
  leaf_prediction: ['mean', 'adaptive']
}
hat_reg_options: {
  grace_period: [200, 400, 600],
  confidence: [1e-3, 1e-4],
  leaf_prediction: ['mean', 'adaptive']
}
sgd_reg_options: {
  loss: ['squared_error', 'huber'],
  penalty: ['l2', 'l1'],
  learning_rate: [
    {lr: 'optimal', eta0: 0.0},
    {lr: 'constant', eta0: 0.01},
    {lr: 'invscaling', eta0: 0.01}
    ]
}
knn_reg_options: {
  k: [3, 6, 10],
  median: [False, True],
  window_size: [1000, 5000]
}